#!/bin/sh
#
# @name Mt_Tri_Exp
#
# @type Tricopter Y+
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN1 motor 2
# @output MAIN1 motor 3
# @output AUX1 yaw servo on motor 1
# @output AUX2 yaw servo on motor 2
# @output AUX3 yaw servo on motor 3
#
# @maintainer DA <dabara2004@yahoo.com>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
        param set THR_MDL_FAC 0.7
        param set CBRK_USB_CHK 197848
        param set MPC_XY_CRUISE 3
        param set MPC_XY_VEL_MAX 10
        param set LNDMC_ALT_MAX 3
        param set RTL_RETURN_ALT 30
        param set COM_DISARM_LAND 5
        param set COM_DISARM_PRFLT 15
        param set SDLOG_PROFILE 11
        param set EKF2_HGT_MODE 1
        param set EKF2_AID_MASK 1

        param set MC_PITCHRATE_D  0.003
        param set MC_PITCHRATE_P  0.15
        param set MC_PITCH_P  6.0
        param set MC_ROLLRATE_D   0.003
        param set MC_ROLLRATE_P   0.15
        param set MC_ROLL_P   6.0
        param set MC_YAWRATE_MAX  120
        param set MC_YAWRATE_P    0.3
        param set MC_YAW_FF   0.35
        param set MC_YAW_P    2.5

        param set MPC_LAND_SPEED 0.7
        param set MPC_TKO_SPEED 1.5
        param set MPC_Z_VEL_MAX_UP 3.0

        param set BAT_N_CELLS 4
        param set BAT_A_PER_V 15.39013031
        param set BAT_V_DIV 10.17793941

fi

# Configure this as Tricopter
set MAV_TYPE 15

# Configure as Generic micro air vehicle
# set MAV_TYPE 0

# configure as Tiltrotor VTOL
# set MAV_TYPE 21

# Set MAIN mixer / Activate outputs
set MIXER tri_exp+
set PWM_OUT 123
set PWM_RATE 400

# Set AUX mixer / Activate outputs
set MIXER_AUX tri_exp+
set PWM_AUX_OUT 123
